--- # tasks/main.yml
- name: Create non-root user
  ansible.builtin.user:
    name: "{{ user_name }}"
    shell: /bin/bash
    groups: sudo
    append: yes
    state: present

- name: Set up SSH directory
  ansible.builtin.file:
    path: "/home/{{ user_name }}/.ssh"
    state: directory
    mode: '0700'
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
  become: true
