--- # tasks/main.yml
- name: Install zsh
  ansible.builtin.apt:
    name: zsh
    state: present
    update_cache: yes
  become: true

- name: Set zsh as default shell
  ansible.builtin.user:
    name: "{{ simpleprod_user }}"
    shell: /bin/zsh
  become: true

- name: Install Starship
  ansible.builtin.shell: curl -sS https://starship.rs/install.sh | sh
  args:
    creates: /usr/local/bin/starship
  become: true

- name: Create Starship config directory
  ansible.builtin.file:
    path: /home/{{ simpleprod_user }}/.config
    state: directory
    mode: '0755'
    owner: "{{ simpleprod_user }}"
    group: "{{ simpleprod_user }}"
  become: true

- name: Configure Starship
  ansible.builtin.template:
    src: starship.toml.j2
    dest: /home/{{ simpleprod_user }}/.config/starship.toml
    owner: "{{ simpleprod_user }}"
    group: "{{ simpleprod_user }}"
    mode: '0644'
  become: true