--- # tasks/main.yml
- name: Install PostgreSQL
  ansible.builtin.apt:
    name: postgresql
    state: present
    update_cache: yes
  become: true

- name: Create database
  community.postgresql.postgresql_db:
    name: "{{ db_name }}"
    state: present
  become: true
  become_user: postgres

- name: Create database user
  community.postgresql.postgresql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    db: "{{ db_name }}"
    priv: ALL
    state: present
  become: true
  become_user: postgres
