name: Lint
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: ShellCheck
        run: find . -name "*.sh" -exec shellcheck {} \;
      - name: Ansible Lint
        run: ansible-lint roles/
      - name: Python Flake8
        run: pip install flake8 && flake8 orchestrator/
